class Cadastro < SitePrism::Page
    element :proxima,:xpath,
    element :nome , :xpath,
    element :email ,:xpath, 
    element :like_yes ,:xpath,
    element :like_no ,:xpath, 
    element :nenhum ,:xpath, 
    element :ep_um ,:xpath, 
    element :ep_dois ,:xpath, 
    element :ep_tres ,:xpath, 
    element :ep_quatro ,:xpath, 
    element :ep_cinco ,:xpath, 
    element :ep_seis ,:xpath, 
    element :ep_sete ,:xpath, 
    element :outro_filme ,:xpath, 
    element :outro_qual ,:xpath, 
    element :personagem ,:xpath, 
    element :check_box, :xpath ,
    element :check_yes, :xpath , 
    element :check_no, :xpath ,
    element :voltar, :xpath,  
    element :salvar, :xpath, 
end